spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.baedal.pass.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO
    com.baedal: DEBUG
    com.baedal.pass.mapper: DEBUG
  
  file:
    name: logs/baedal-server.log
  
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"